import { createHash } from "node:crypto";
import { join, relative } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const AGENT_DIRECTORY = join(ROOT, "agents");
const OUTPUT_DIRECTORY = join(ROOT, "codex", "agents");
const GENERATOR_SCHEMA_VERSION = "1";

const PRELUDE = `# Codex compatibility prelude (construction-skills)

You are running as a Codex custom agent adapted from a Claude Code agent
definition in this plugin. Preserve the role, constraints, and output style of
the canonical body below. The construction decision rules are the point of this
agent; the runtime translation below never relaxes them.

## Runtime translation (Claude -> Codex)

| Claude concept | Codex-native behavior |
|---|---|
| \`Read\` / \`Grep\` / \`Glob\` | Codex filesystem tools or shell (\`rg\`, \`cat\`, \`find\`) |
| \`Write\` / \`Edit\` | Codex \`apply_patch\` or the equivalent file-edit tool |
| \`Bash\` | Codex shell execution |
| \`Skill(name)\` | Open and follow the matching \`SKILL.md\` from the installed skills; never invent a skill |
| Source \`model:\` | Informational only - inherit the parent Codex session model |

## Rules

- Prefer tools available in this Codex session. Where a Claude-only tool is
  missing, use the nearest Codex equivalent and note the substitution only when
  it changes the result.
- Never relax a sourcing, uncertainty, or human-approval rule from the body
  below to fit a runtime limitation. Report the limitation instead.

---
`;

interface AgentRecord {
  agentName: string;
  description: string;
  generatedFile: string;
  generatedHash: string;
  sourceHash: string;
  sourceName: string;
  sourcePath: string;
  sourceVersion: string;
}

const sha256 = (value: string): string =>
  `sha256:${createHash("sha256").update(value).digest("hex")}`;

export const parseFrontmatter = (text: string) => {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(text);
  if (!match) throw new Error("agent file is missing YAML frontmatter");
  const frontmatter = Bun.YAML.parse(match[1] ?? "") as Record<string, unknown>;
  const name = frontmatter?.name;
  const description = frontmatter?.description;
  if (
    typeof name !== "string" ||
    name.length > 64 ||
    !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name)
  )
    throw new Error("Agent name must be a lowercase slug (1-64 characters)");
  if (typeof description !== "string" || !description.trim())
    throw new Error("Agent description is required");
  return {
    body: text.slice(match[0].length),
    frontmatter,
    name,
    description: description.trim(),
  };
};

const toTomlString = (value: string): string => JSON.stringify(value);

export const renderAgent = (
  sourcePath: string,
  text: string,
  skillPrefix = "../../skills/",
) => {
  const { body, frontmatter, name: sourceName, description } = parseFrontmatter(text);
  const agentName = sourceName.replace(/-/g, "_");
  const instructions = `${PRELUDE}\n${body.trim().replaceAll("../skills/", skillPrefix)}\n`;
  const sourceHash = sha256(text);
  const header = [
    "# Generated by scripts/generate-codex-agents.ts - DO NOT EDIT BY HAND",
    `# source: ${relative(ROOT, sourcePath)}`,
    `# source_version: ${frontmatter.version ?? "unversioned"}`,
    `# source_hash: ${sourceHash}`,
    `# generator_schema_version: ${GENERATOR_SCHEMA_VERSION}`,
  ].join("\n");
  const content = [
    header,
    "",
    `name = ${toTomlString(agentName)}`,
    `description = ${toTomlString(description)}`,
    `developer_instructions = ${toTomlString(instructions)}`,
    "",
  ].join("\n");
  return {
    agentName,
    content,
    description,
    generatedFile: `${sourceName}.toml`,
    sourceHash,
    sourceName,
    sourcePath,
    sourceVersion: String(frontmatter.version ?? "unversioned"),
  };
};

export const buildCodexAgents = async () => {
  const glob = new Bun.Glob("*.md");
  const files: string[] = [];
  for await (const file of glob.scan({ cwd: AGENT_DIRECTORY })) {
    files.push(join(AGENT_DIRECTORY, file));
  }
  files.sort();
  const outputs: Array<{ content: string; path: string }> = [];
  const records: AgentRecord[] = [];
  for (const file of files) {
    const rendered = renderAgent(file, await Bun.file(file).text());
    const path = join(OUTPUT_DIRECTORY, rendered.generatedFile);
    if (outputs.some((output) => output.path === path))
      throw new Error("Duplicate agent name");
    outputs.push({ content: rendered.content, path });
    records.push({
      agentName: rendered.agentName,
      description: rendered.description,
      generatedFile: rendered.generatedFile,
      generatedHash: sha256(rendered.content),
      sourceHash: rendered.sourceHash,
      sourceName: rendered.sourceName,
      sourcePath: relative(ROOT, rendered.sourcePath),
      sourceVersion: rendered.sourceVersion,
    });
  }
  const manifest = `${JSON.stringify(
    {
      agents: records,
      generatorSchemaVersion: GENERATOR_SCHEMA_VERSION,
      plugin: "construction-skills",
      schemaVersion: "1",
    },
    null,
    2,
  )}\n`;
  outputs.push({ content: manifest, path: join(OUTPUT_DIRECTORY, "manifest.json") });
  return outputs;
};

export const runFromCli = async (args: string[]): Promise<void> => {
  const checkOnly = args.includes("--check");
  const outputs = await buildCodexAgents();
  const stale: string[] = [];
  for (const output of outputs) {
    const file = Bun.file(output.path);
    const current = (await file.exists()) ? await file.text() : null;
    if (current === output.content) {
      continue;
    }
    stale.push(relative(ROOT, output.path));
    if (!checkOnly) {
      await Bun.write(output.path, output.content);
    }
  }
  if (checkOnly && stale.length > 0) {
    process.stderr.write(
      `Codex agent adapters are stale. Run bun run codex:agents\n${stale
        .map((path) => `  - ${path}`)
        .join("\n")}\n`,
    );
    process.exitCode = 1;
    return;
  }
  process.stdout.write(
    checkOnly
      ? "Codex agent adapters are current.\n"
      : `Wrote ${stale.length} Codex agent file(s).\n`,
  );
};

if (import.meta.main) {
  await runFromCli(Bun.argv.slice(2));
}
